# Generated by Django 5.1.2 on 2024-11-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediHubapp', '0004_alter_recommendation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
    ]
