# Generated by Django 5.1.2 on 2024-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHubapp', '0005_remove_recommendation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='medi@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
