# Generated by Django 5.1.2 on 2024-12-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediHubapp', '0006_company_email_company_website_medicine_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company',
        ),
        migrations.AddField(
            model_name='medicine',
            name='companies',
            field=models.ManyToManyField(related_name='medicines', to='MediHubapp.company'),
        ),
    ]
